### ISSUE TITLE
Revamping the Backend UI for matching-context : create product targeted fields

### ISSUE THREAD

**Issue by zhinu** [dis-moi/backend#448]
## Stakes
Transitioning from regex and xpath to nocode

## Context
Today, the matching context has the following fields 
<img width="206" alt="Capture d’écran 2021-09-13 à 13 01 06" src="https://user-images.githubusercontent.com/75084558/133072532-acf7f354-3f2f-41e4-a9f7-93c4e1e5afe5.png">

The fields Regex target the url whereas xpath target the Document Object Model (DOM). Those two fields, need a special expertise to be used, hence not user friendly

## Wished evolution
Web pages often have a similar structure : 

### Product
- ~Title~ Name
- Category
- Description
- Price

###  Offer
- Location

The previous parts should be targetable directly from the backend.

### For Title, Category, and Description the possibility would be to have the following options logical connectors 
AND OR EXCEPT
i.e. 
(term1 and term2) or term3 except term4

### For Price, the following possibility should be to have the following mathematical functions
lower than <, greater than, lower than or equal to <=, greater than or equal to >=

Ie.
lower than or equal to <= number 1 and greater than > number 2

### For the last part location, a more intuitive way would be to select cities or regions directly from a dropdown list or a map.

**Comment by lutangar** [comment]
> https://schema.org/Product

**Comment by MaartenLMEM** [comment]
@lutangar I just commented the related issue on mobile repo : https://github.com/dis-moi/mobile/issues/239#issuecomment-925969271 
Afterwards, don't you think the BO/API should do this work. 
And clients such as mobile app would make his own "advanced" translations only if BO is less appropriate to make it (for efficiency/privacy... reasons or others) ?

**Comment by MaartenLMEM** [comment]
Ok discussed friday, there a misunderstanding. 
Let's review this and we ll make nex fields later

**Comment by MaartenLMEM** [comment]
Tesed on BO. It s ok, but during next step it will be important to discuss about how it will be used by extensions et mobile apps. 

See for example [this notice in staging](https://staging-notices.lmem.net/admin/?entity=Notice&action=edit&menuIndex=0&submenuIndex=-1&sortField=id&sortDirection=DESC&page=1&referer=%252Fadmin%252F%253Fentity%253DNotice%2526action%253Dlist%2526menuIndex%253D0%2526submenuIndex%253D-1%2526sortField%253Did%2526sortDirection%253DDESC%2526page%253D1&id=1632) 
=> An important rule will habe to add on extension part is the following : If there is product name filled, ignore this regex. Otherwise it will match on each product page of Amazon.
